/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Startup Delay
 #	author : miyako
 #	2015/10/15
 #
 # --------------------------------------------------------------------------------*/


void InitPlugin();

// --- Startup Delay
void Get_startup_delay_time(sLONG_PTR *pResult, PackagePtr pParams);
